language: ruby
rvm:
  - 2.4.0
cache: bundler

sudo: required
dist: trusty
addons:
  apt:
    packages:
      - chromium-chromedriver
  chrome: stable

before_script:
  - source .travis_config.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3