dist: trusty

language: ruby
rvm:
  - 2.4

sudo: required

addons:
  chrome: stable

before_install:
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache: bundler

before_script: source .travis_config.sh