version: '3'
services:
  prod:
    build:
      context: .
      args:
        RAILS_ENV: production
    volumes:
      - CognitiveBank:/CognitiveBank/public
    ports:
      - "3000:3000"
    env_file:
      - .env